[build]
  command = "npm run build"
  publish = "dist"

# Simple redirects for Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/game.html*"
  to = "/game.html"
  status = 200
