# No build needed, just static files

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/game.html*"
  to = "/game.html"
  status = 200
